### ISSUE TITLE
Creating UiGridPanel

### ISSUE THREAD

**Issue by safibarri** [m-m-m/ui-api#5]
UiGridPanel is required for layouting child widgets (`UiRegularWidget`) in a grid.

Status:
* [x] added interfaces to `ui-api`
* [x] added implementation to `ui-fx`
* [x] added implementation to `ui-tvm`
* [x] added implementation to `ui-test`
* [ ] added implementation to `ui-android`
* [x] added example to `ui-demo`

**Comment by hohwille** [comment]
Should the grid panel have a fixed number of rows/columns?
How should the API be to add children into the grid? How about row-span and col-span?
This is all complicated and to design an easy to use API that is both flexible and prevents mistakes is not easy. Must UI toolkits fail to provide a good API for this problem (e.g. JavaFx where it is flexible but pure pain to e.g. insert a new row).

**Comment by hohwille** [comment]
Most generic API is something like this:
`gridPanel.setChild(UiRegularWidget child, int row, int column, int rowSpan, int colSpan)`

More user-friendly API might be something like this:
```
UiGridRow row = gridPanel.addRow();
row.addChild(child);
row.addChild(extraWideChild, colSpan);
```

However, when the grid is not row-oriented or you want to have row-spans, the second API is not so great. Question is if the latter are untypical use-cases and we should focus on happy path.

**Comment by hohwille** [comment]
Actually the API IMHO still needs a slight redesign.
Currently adding/setting children in `UiGridRow` require the position of the child in the row.
If you are using `colspan` this position is not the index of the column but really the child index.
IMHO this can be quite confusing for the end-user.
So it may be better to remove `addChild` entirely and replace the current `setChild` method with:
```
  void setChild(UiRegularWidget child, int column, int colspan, int rowspan);
```

So the second argument is always the number of the column in the grid where to set the child. Even if the `UiGridRow` is empty then calling `setChild` with `column=5` would place the child into that column of the row. For the web (ui-tvm) this would mean that according blank cells have to be added before.

**Comment by hohwille** [comment]
Two problems with the API are remaining:
1. If you set a children in a cell that is spaned via `colspan`:

```
|A0|A1|A2|A3|
|B0   |B2   |
```
Now if you would insert `B1` into the second row at column `1` (2nd column) an `IndexOutOfBoundsException` will be thrown by the TeaVM implementation (otherwise `B2` would be shifted to the right below `A3`) and the JavaFx implementation will cause some unpredictable result (child may be invisible or overlap `B0`).

2. In case you are using `rowspan` it gets even more problematic:
```
|A0|A1|A2|A3|
|A0|  |  |  |
```

Now if you insert `B1` into the second row at column `1` (2nd column)  this is currently not handled.
So it will work as expected in JavaFx and for TeaVM it will be placed in 3rd column instead of 2nd. Therefore a row would need to handle the rowspans of all above columns to ensure a consistent toolkit-agnostic behavior. Implementing this will IMHO very tricky.

Conclusion: While 1. is OK for me, the problem 2. is inacceptable and we have to find a solution.
The most simple solution would be to drop support for `rowspan`. Otherwise I have to rethink the API design of `UiGridRow` once more...

**Comment by hohwille** [comment]
Users need all the flexibility and features including `rowspan`. So there seems no other way to me then changing the design entirely again. IMHO it has to be like in HTML with tables:
https://html.com/tables/rowspan-colspan/#rowspan_8212_Code_Example
So the developer needs to know about the spans and can not place in absolute columns.
This makes it more complex for the developer/API-user but otherwise I see no consistent solution.

**Comment by hohwille** [comment]
The main problem is that the model/API of JavaFx and HTML are entirely different. Hence I can not entirely get around a tricky implementation that deals with the rowspans of rows above - either in JavaFx or for TeaVM.
Arguments for the `addChild` with child-index approach:
* more complexity needed for JavaFx implementation where performance nuances have less impact when running on a full-fledged JVM rather than in emulared JavaScript inside browser. Also the API is then more aligned with the API of other panels (`getChildCount()` returns the number of chilren, `getChild(int)` returns the n-th child, etc.). No runtime errors when children are set in spanned cells.
Arguments for the `setChild` with column-index approach:
* A little easier for developers to code layouts without mistakes.

Finally the android model is much worse (as always) as you have to define the number of columns and rows in advance for the grid to work. We can try to inernally store the child widgets and create the grid lazy (e.g. when it is attached to its parent), but really dynamic grid code will not work on android then. We might have to provide an API to set to columns and rows programmatically for UI developers that want to support android.

**Comment by hohwille** [comment]
Now all should be fine. JavaFx implementation was not as tricky as expected. However, surely there will be a bug in an edge-case with row-spans that needs to be found and fixed.
API can be considered as ready now.
